### ISSUE TITLE
Accented characters not displaying correctly

### ISSUE THREAD

**Issue by pixelbreeze38** [mkiol/dsnote#106]
I've noticed an issue where accented characters are not being correctly inputted when sending text to the active window. Characters without accents are processed fine, but accented characters like 'ã', 'ê', 'á', do not appear as expected in the application.

**Comment by mkiol** [comment]
Thanks for reporting.

It should work but you have to have appropriate keyboard layout installed in your system. 

It is not documented, but to make "sending text to the active window" functional, your keyboard must be able to generate characters you want to send. For instance to send Greek characters you need to have Greek keyboard layout installed in your system. You can check current layouts with following command:

```
setxkbmap -query
```

What language you have set in your system and what language you use for STT?

**Comment by pixelbreeze38** [comment]
Thank you for your quick response.
I use Portuguese for STT. Here's the output of setxkbmap -query on my system:

rules: evdev
model: pc105
layout: br,us
variant: ,

**Comment by mkiol** [comment]
Can confirm. It doesn't work.

This feature ("sending text to the active window") is implemented in such a way that the application imitates pressing a virtual keyboard. This makes it possible to insert any text outside the application. The key problem is finding the right combination of keystrokes to get the character you need. This is trivial for English because English characters map almost 1-1 to real keys on the keyboard. It's more complicated when you want to find a combination of characters that don't exist in English. Typically, you use `Left Alt+<something>` to create a modified latin letter. For example, to get `ó`, you type `Left Alt + o` (PL layout). This mechanism is implemented and works fine, but other combinations are not supported right now.

Using Brazilian keyboard layout, how can I type these characters? I mean what is the right key combination? 

- `ã`
- `ê`
- `á`

**Comment by pixelbreeze38** [comment]
To type the accents you asked about on a Brazilian keyboard:

* ã: Press ~ then a.
* ê: Press Shift + ^ then e.
* á: Press ´ then a.
* à: Press Shift + ` then a.

The tilde, circumflex, acute and grave accents act as dead keys, waiting for the next character to be pressed.

**Comment by mkiol** [comment]
Thanks for the explanation. This is much more complicated than I anticipated!

I did quick research and I think I will be able to fix this :)

**Comment by pixelbreeze38** [comment]
That’s great! Excited to use this feature in Portuguese. Thanks!

**Comment by mkiol** [comment]
Fix: 60f15d6

The fix will be included in the next release.

**Comment by mkiol** [comment]
Just letting you know if you want to test it before the release. The fix is included in beta version in [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111).

**Comment by pixelbreeze38** [comment]
The fix works like a charm! Thank you!

**Comment by mkiol** [comment]
Fix is included in v4.5.0.

**Comment by miguel-negrao** [comment]
In the latest version, when using the xdo method of input into active window, this problem manifests again. Switching to legacy works though.

**Comment by mkiol** [comment]
@miguel-negrao Thank you for your report. When you say "latest", do you mean version 4.8.3 or 4.9.0-beta from the flathub-beta channel?

**Comment by tsardelli-dh** [comment]
Hi @mkiol , I can confirm I have the same issues as @miguel-negrao  and I'm using the latest stable (4.8.4) installed with Flatpak on Ubuntu 24.04.
In my case the language is Italian but my keyboard is set to English with a compose key (right alt) for accents and special characters.
If I use the XDO input method, the accented characters don't show up at all. If I switch to "legacy" (without specifying a compose file though, because I don't know what I should put there), I get the letters but without the accents.

To clarify:
```shell
# Expected
però sarà così

# XDO
per sar cos

# Legacy
pero sara cosi
```

Let me know if I can provide additional info (logs, etc.) to help troubleshooting, or if I should create a new issue.

P.S. Thanks a lot for this application because it's really awesome ❤️

**Comment by tsardelli-dh** [comment]
Just a follow-up with two workarounds that I found for my setup (Ubuntu 24.04, Flatpak version 4.8.4, X11, US layout with compose key):

**XDO:** increasing *Keystroke delay* to ~250 in the advanced settings makes accents work, but typing becomes quite slow.

**Legacy (better):** works at the default delay (20) with a custom compose file containing only `Multi_key` sequences. Since the Flatpak sandbox can't read the home folder, I placed it in the app's config dir and set that path in `Settings → Advanced → Insert into active window → Compose file`: `~/.var/app/net.mkiol.SpeechNote/config/Compose`


```
# Multi_key-only sequences: every key in each sequence exists on a plain
# US layout with a Compose key (e.g. compose:ralt). No dead keys.

# Grave-accented vowels
<Multi_key> <grave> <a>		: "à"	agrave
<Multi_key> <grave> <e>		: "è"	egrave
<Multi_key> <grave> <i>		: "ì"	igrave
<Multi_key> <grave> <o>		: "ò"	ograve
<Multi_key> <grave> <u>		: "ù"	ugrave
<Multi_key> <grave> <A>		: "À"	Agrave
<Multi_key> <grave> <E>		: "È"	Egrave
<Multi_key> <grave> <I>		: "Ì"	Igrave
<Multi_key> <grave> <O>		: "Ò"	Ograve
<Multi_key> <grave> <U>		: "Ù"	Ugrave

# Acute-accented vowels
<Multi_key> <apostrophe> <a>	: "á"	aacute
<Multi_key> <apostrophe> <e>	: "é"	eacute
<Multi_key> <apostrophe> <i>	: "í"	iacute
<Multi_key> <apostrophe> <o>	: "ó"	oacute
<Multi_key> <apostrophe> <u>	: "ú"	uacute
<Multi_key> <apostrophe> <A>	: "Á"	Aacute
<Multi_key> <apostrophe> <E>	: "É"	Eacute
<Multi_key> <apostrophe> <I>	: "Í"	Iacute
<Multi_key> <apostrophe> <O>	: "Ó"	Oacute
<Multi_key> <apostrophe> <U>	: "Ú"	Uacute

# Other characters STT models commonly emit
<Multi_key> <comma> <c>		: "ç"	ccedilla
<Multi_key> <comma> <C>		: "Ç"	Ccedilla
<Multi_key> <asciitilde> <n>	: "ñ"	ntilde
<Multi_key> <asciitilde> <N>	: "Ñ"	Ntilde
<Multi_key> <quotedbl> <u>	: "ü"	udiaeresis
<Multi_key> <quotedbl> <o>	: "ö"	odiaeresis
<Multi_key> <quotedbl> <a>	: "ä"	adiaeresis
<Multi_key> <asciicircum> <e>	: "ê"	ecircumflex
<Multi_key> <asciicircum> <a>	: "â"	acircumflex
<Multi_key> <asciicircum> <o>	: "ô"	ocircumflex

# Typographic punctuation
<Multi_key> <apostrophe> <apostrophe>	: "’"	rightsinglequotemark
<Multi_key> <less> <less>	: "«"	guillemotleft
<Multi_key> <greater> <greater>	: "»"	guillemotright
<Multi_key> <period> <period>	: "…"	ellipsis
<Multi_key> <equal> <e>		: "€"	EuroSign
<Multi_key> <o> <o>		: "°"	degree
```
