### ISSUE TITLE
[FEATURE REQUEST] Autoplay TTS Output

### ISSUE THREAD

**Issue by kazcat0** [mkiol/dsnote#119]
Some speech-to-text-to-speech software have a function where the STT output autoplays so people can use it as a digital voice to use in videos, livestreams, voice chat, or video games for various reasons including privacy. This software is mostly limited to Windows, so it would be nice to see Linux-based software have this ability, especially since Speech Note can be used on older and lower powered hardware.
Thank you!

**Comment by mkiol** [comment]
Thanks for bringing an interesting use case. I like "privacy" aspect. It fits well in to Speech Note :)

I see it as "repeat mode". After STT decoding, TTS is started automatically for the last input.

I also wonder if SN could provide (on system level) a "fake" microphone that could be used instead of the real one. This can't be very difficult to implement 🤔 .

**Comment by Melechtna** [comment]
I'm actually trying to workout how to do this in pipewire, creating a virtual microphone is easy enough, but I'm having trouble working out how to pipe the audio into the virtual microphone.

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes:

- Echo mode. After processing, the decoded text will be immediately read out using the currently set Text to Speech model.

BTW, I'm still thinking about the "virtual microphone" feature... but I haven't had time to dig into it.

Video presentation of all the new features introduced in version 4.7.0: https://www.youtube.com/watch?v=cEht4Fts6Bo
