### ISSUE TITLE
Edit function?

### ISSUE THREAD

**Issue by Getarhubar** [mkiol/dsnote#160]
Hello mkiol

I have been using your wonderful program for the last couple of months and absolutely love it! Thanks so much for developing it, it is really helping people :)

I wonder whether at some point you might consider adding an edit function? If I am speaking and I want to edit a sentence that I spoke earlier (e.g. 20 sentences ago), or to add something at that point in the paragraph (further up e.g. 20 sentences ago) it won't let me do that, it will only add the words at the end of the last sentence spoken. So say earlier in the paragraph I highlight a word to try to change it or I put my cursor somewhere earlier in the paragraph (at the point where I want to add a sentence/sentences), it will automatically type at the end instead. I hope my request makes sense?

Anyway I wanted to make the request and will leave it with you to consider

Many thanks

**Comment by mkiol** [comment]
Thanks for the report.

Indeed, each new sentence is always inserted at the end of the text. I totally agree that inserting in the cursor position would be much better. I will correct this in the next version.

**Comment by Getarhubar** [comment]
Great thanks mkiol! :)

**Comment by mkiol** [comment]
Added in 2fb3780ae14efe5a1e0948e1317581377288b109 and released in Beta version.

More details how to install Beta can be found [here](https://github.com/mkiol/dsnote/issues/179).

To insert at the cursor position you need to change _Text appending mode_ in the settings.

![image](https://github.com/user-attachments/assets/44c1a7df-0769-49e2-9ae2-d92ab589a371)

The cursor is always visible (even when the text field is not active), so you know where the text will be inserted.

![image](https://github.com/user-attachments/assets/5aff1fcb-34ee-4232-a45f-154f4b853032)

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes:

- New modes for inserting text at the cursor position or replacing the current note. To insert text at the cursor position rather than at the end of the note, change _Text appending mode_ option to _Add at the cursor position_ in the settings. When the _Replace an existing note_ option is set, whenever new text is added, it will replace the existing note.

Video presentation of all the new features introduced in version 4.7.0: https://www.youtube.com/watch?v=cEht4Fts6Bo
