### ISSUE TITLE
Flatpak won't launch

### ISSUE THREAD

**Issue by LalOpen** [mkiol/dsnote#164]
Heyy! I installed Speech Note through Flathub, but the flatpak app won't launch.

This is the output of the following command : 
```
flatpak run net.mkiol.SpeechNote --gpu-scan-off --verbose
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

Distro : Debian 12.7
Kernel : 6.1.0-25-amd64
DE : GNOME 43.9
CPU : 11th Gen Intel i7-1185G7 (8) @ 4.800GHz
GPU : Intel TigerLake-LP GT2 [Iris Xe Graphics]
on Wayland

I do have qt apps that runs perfectly well.

Is it an issue related to the app or to my configuration? If it is that second option, could you give me pieces of advice to make Speech Note work on my computer?

**Comment by mkiol** [comment]
Hi. Thank you for reporting.

I tested latest Speech Note on Debian 12.7+GNOME+Wayland and didn't have this problem, so it is something related to the specific configuration in your system. It smells like strictly Flatpak related problem. 

Sorry for the question, but have you updated all installed Fatpak packages? You can do this with the `flatpak update` command.

It looks that the program tries to start in X11 mode instead of Wayland. You could force QT Wayland by setting QT_QPA_PLATFORM variable in the Flatpak sandbox. You can do it like this:

```
flatpak run --env=QT_QPA_PLATFORM=wayland net.mkiol.SpeechNote --verbose
```

or 

```
flatpak run --env=QT_QPA_PLATFORM=wayland-egl net.mkiol.SpeechNote --verbose
```

Did this help?

**Comment by LalOpen** [comment]
Thank you very much for your answer! I did have all Flatpak packages up to date.

But I've just tried your first command and Speech Note was finally able to launch.
So that's great, I'm now able to convert some audio notes for my studies into text ^^ (didn't want to use some weird proprietary-freemium websites !)

**Comment by mkiol** [comment]
Cool. Glad I could help.

BTW, with [FlatSeal](https://flathub.org/apps/com.github.tchx84.Flatseal) app, you can easily make this variable permanent and launch app from the app drawer instead of terminal.

![image](https://github.com/user-attachments/assets/f55cb531-d60f-43e8-a6cf-e1a27bee1c82)
