### ISSUE TITLE
Add WhisperSpeech Medium TTS/Voice Cloning model

### ISSUE THREAD

**Issue by JamesClarke7283** [mkiol/dsnote#166]
WhisperSpeech has a Medium model now:

https://huggingface.co/WhisperSpeech/WhisperSpeech

It might be more accurate.

**Comment by mkiol** [comment]
Also it looks that new models support 7 languages!

Unfortunately, these new models do not currently work with the engine code that was published [here](https://github.com/collabora/whisperspeech). The WhisperSpeech team needs to release an update for their project.

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes:

- New _WhisperSpeech Small_ model for: English, Italian, German, French, Spanish, Dutch and Portuguese

I didn't enable the "Medium" model because I wasn't able to test it properly. It seems that "Medium" has very high GPU memory requirements, and my not-so-new graphics card was not able to run it :/
