### ISSUE TITLE
STT using audio file reliably crashes Linux system with kernel BUG: soft lockup - CPU#N stuck

### ISSUE THREAD

**Issue by ousado** [mkiol/dsnote#170]
STT using an audio file reliably crashes the system with kernel message BUG: soft lockup - CPU#N stuck 
where N is some number. 

This is using the current stable flatpak Speech Note version 4.6.1 on Ubuntu 22.04. 
It's impossible to kill dsnote and bswrap when this occurs. 
Using hardware acceleration for STT doesn't affect the crashes. Also STT using the microphone seems to work flawlessly, and using the commandline version of whisper with the same settings for audio file STT also works without issues. The problem seems to be related to how flatpak is accessing the audio file. 

Might be related to this:
https://bbs.archlinux.org/viewtopic.php?id=298343

**Comment by mkiol** [comment]
Thanks for reporting.

Since the most likely cause of this problem is in the Portal or even the kernel, I won't be able to do much. But I may be able to work around it. 

Questions:

1. Does this problem only occur when accessing a file outside the Flatpak sandbox? The default directory permissions for Speech Note are: Desktop, Download, Music, Documents and Video, but you can access files outside the sandbox when using the Portal (=Open File dialog).
2. If the problem is related to Portal only, you can use a drag-and-drop gesture to transcribe the file instead. The file must be in location accessible to Speech Note. Does this method also not work?

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

If the problem persists with v4.7.0, please reopen.
