### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mr-tron** [mkiol/dsnote#175]
Hi. Can you please build new releases more often? I see a lot of useful changes in commits since last release 3 months ago.
Or maybe you can share instruction how i can install beta version with flatpack.

**Comment by mkiol** [comment]
Hi. I try to publish a new release when I gather some new features or when there is some critical bug. Unfortunately, lately I've been going quite slowly with development and there isn't much of it. Definitely, not enough for a new release :/

I plan to push first 4.7-beta version soon (maybe in 2 weeks).

To test beta you need to add `flathub-beta` repository:

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
```

and install Speech Note from `flathub-beta`:

```
flatpak install flathub-beta net.mkiol.SpeechNote
```

If you have both regular and beta versions installed, to run beta use `--branch=beta` option:

```
flatpak run --branch=beta net.mkiol.SpeechNote
```

At the moment, the beta channel contains the same version as the regular one, because I have not yet released any beta version.

**Comment by mkiol** [comment]
New Beta release is out. More details can be found [here](https://github.com/mkiol/dsnote/issues/179).

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

Video presentation of all the new features introduced in version 4.7.0: https://www.youtube.com/watch?v=cEht4Fts6Bo
