### ISSUE TITLE
[idea] Translate option for non-english whisper models

### ISSUE THREAD

**Issue by szopin** [mkiol/dsnote#4]
As whisper is now supported (great stuff, thank You) it would be really cool if one could tick a box maybe and use the ability of whisper to translate to english, would be really handy when going abroad to be able just record people speaking local language and get instant translation

**Comment by mkiol** [comment]
Actually this checkbox is already there but hidden because translations are not good enough. 

 https://github.com/mkiol/dsnote/blob/41fd318d7d45a3c770a6cc713f926f98e1344db4/sfos/qml/SettingsPage.qml#LL133C24-L133C24 

Translation to english seems to work well but only with 'small' and larger models. On 'tiny' I've got mixed results, sometimes text was quite accurate but sometimes only partially translated or just made up. What is funny, 'medium' model can translate also from english to, for instance, polish without any 'checkbox'. Whisper has huge potential :) 

I think 'translation' feature has to wait for enabling Whisper larger models.

**Comment by szopin** [comment]
Yeah, tiny was a bit lacking in my limited testing. Btw how did you get it to translate to non-english?

**Comment by mkiol** [comment]
> Btw how did you get it to translate to non-English?

Nothing extra ordinary is  needed. Just use multilang small or medium model with language set to 'pl'. Then say something in English. The model outputs text in Polish! I also tried this with German and Czech and it seems not working, but works for Spanish. Very wired.

**Comment by mkiol** [comment]
This option (Translate to English) is now available in desktop version of Speech Note.
