### ISSUE TITLE
Add option for bigger whisper models

### ISSUE THREAD

**Issue by szopin** [mkiol/dsnote#5]
Looking through whisper.cpp it needs 3x less memory than the original, which would make it possible to run even large model on xperia 10 III (3.3GB vs 10GB), this would probably be overkill, especially speed would suffer a lot, but adding small and medium would probably make sense

**Comment by mkiol** [comment]
It is possible but the problem is not in memory but in computation speed. 

Here are the results from my experiments on Xperia 10 III:

1s of speech data needs Xs of processing time:
- en-tiny: 1.06s 
- en-base: 2.72s
- en-small: 10.30s
- en-medium: 30.58s

So, for real-time experience only 'tiny' is usable unfortunately. The results on Xperia 10 are an order of magnitude worse :(

Whisper.cpp project is under intensive development, so I expect (maybe I hope) that performance will increase soon. Maybe in couple of weeks it will be good enough for larger models.

**Comment by szopin** [comment]
Looks like this problem: https://github.com/ggerganov/whisper.cpp/issues/599 shame.
The python version with small model might be the way to go for now for translations on the go

**Comment by mkiol** [comment]
Bigger models (Small and Medium) are available in desktop version.
