### ISSUE TITLE
stdout option please

### ISSUE THREAD

**Issue by ye110wd** [mkiol/dsnote#54]
Every day I use this for reading large chunks of text.

Speech Note is writing about 6GB of wave files to disk every day because I use it a lot.

Any chance of having it output sound without writing to disk?

**Comment by mkiol** [comment]
Thank you for the report.

> Speech Note is writing about 6GB of wave files to disk every day

That's a lot! I'm impressed :)

Speech Note caches all encoded sentences in wav files. The cache is cleared when app starts. Cache speeds up the encoding and has a lot of other advantages... but I can imagine that encoding so much text could take up a lot of space on your hard drive. If the problem is only size, maybe a good solution would be to store files in more effective format, like flac or mp3. I'm working right now on new release and I can add this "compressed cache" feature.

BTW, you can test upcoming release by installing Speech Note from  [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111).

**Comment by mkiol** [comment]
I've added "Cache compression" in 6e24e5616e85f5870d0d38b04d4ec4253f76d5ee. The required storage space is much smaller now. 

This change is included in the recent 4.3.0 version.

If this doesn't solve the problem, please re-open the issue.
