### ISSUE TITLE
Call dsnote system wide, read highlighted text from other applications

### ISSUE THREAD

**Issue by ebenfarnworth** [mkiol/dsnote#63]
Amazing to have this software.

I'm trying to send selected text to speech note from other applications and have it read the text. I was able to do this with mimic 3 by running this as a custom keyboard shortcut from KDE or gnome:
`/home/mimic3/.venv/bin/mimic3 --voice en_US/vctk_low --interactive "$(xclip -selection primary -out)"`

Documentation I made for Linux TTS system integration:
https://zenquest.co/team/eben-farnworth/rabbitwhole/text-to-speech-on-linux-ai-rising
https://zenquest.co/team/eben-farnworth/rabbitwhole/text-speech-tts-linux

I see that I can call speech note from the command line to start reading or start reading the clipboard. What would be the best way to send selected text from anywhere on the system to speech note and have it start reading in one command?

**Comment by mkiol** [comment]
Thank you for the question.

As you noticed, the only way (at least right now) is to use clipboard as a sort of "API". You can trigger reading text from a clipboard with command line or DBus call like this:

```
flatpak run net.mkiol.SpeechNote --action start-reading-clipboard
```

```
gdbus call --session -d net.mkiol.SpeechNote -o /net/mkiol/SpeechNote -m org.freedesktop.Application.ActivateAction "start-reading-clipboard" "[]" "{}"
```

You can list all supported "actions" with 

```
flatpak run net.mkiol.SpeechNote --help
```

"Actions" and DBus calls work the best when app is already started because app launch is not immediate and there will be delay between call and reading. 

If you are on X11 you can use built-in "Global Shortcut" as well.

Sadly I didn't find any other way (other than system clipboard), to capture any arbitrary text. So "read the selected text" is not possible and I don't know how to implement it. 

It seems that a more proper way to do it is to integrate via [Speech Dispatcher](https://freebsoft.org/speechd) daemon. I've already seen projects that tried to use Piper engine to do so. For example [Pied](https://pied.mikeasoft.com/) and [this](https://github.com/rhasspy/piper/issues/285). I didn't investigate all the possibilities  yet.

Speech Note is a "fat" GUI app and, in general, it is not meant to be use for integration. If you are looking something lightweight and headless probably [Piper](https://github.com/rhasspy/piper) is a best solution.

**Comment by Kentoseth** [comment]
@ebenfarnworth I see that you are using KDE, so I might suggest you try this solution using Orca and Pied:

https://www.kentoseth.com/posts/2023/dec/29/install-software-to-help-visually-impairedblind-people-use-linux/

**Comment by mkiol** [comment]
I think the question has been answered, so closing.
