### ISSUE TITLE
Markdown formatting removed

### ISSUE THREAD

**Issue by devSJR** [mkiol/dsnote#72]
Would it be possible to preserve Markdown formatting in text translations?
When I paste a text in Markdown markup language, most syntax elements (lists, headings) get removed or get edited (see _italic_ -> 'italic').

![grafik](https://github.com/mkiol/dsnote/assets/5408324/1a09010a-fc34-4e49-afd4-daf8305adce3)

Speech Note 4.3.0

**Comment by mkiol** [comment]
Thanks for reporting.

Unfortunately, Bergamot (library that is used for translations) does not directly supports Markdown, but it supports HTML formatting. Thanks to your report, I've discovered that I didn't enable "keeping of HTML tags", so this will be fixed in the next release.

Just thinking... Since HTML formatting works (or will be), maybe I can implement simple Markdown <=> HTML conversion in pre and post processing of the text. This might work 🤔 Looking for the right library...

**Comment by devSJR** [comment]
Okay, I guess the all-time popular _pandoc_ might be our friend in this case. 
But I think this will not be trivial because it would be challenging to guess the mime type before you process something.

Edit: If I understand your commit 7e8217b3143fa7ad74a3c07e0b8fe99bfe3dfa58 correctly, you are not using a heuristic to guess the mime type, but you give the user an option in the interface. This is a practical solution.

**Comment by mkiol** [comment]
> I guess the all-time popular pandoc might be our friend

Indeed `pandoc` is a very powerful library but it has one "flaw" - it is written in Haskell! I didn't find any easy way to integrate it to c/c++ program. Fortunately, I've managed to find two nice c++ libraries for html2md and md2html... and everything works quite well :)

> but you give the user an option in the interface

Exactly

Additionally I also added support for SRT Subtitles, so you can translate subtitles without breaking the format.

I have to resolve few bugs I found and I'm ready to push new beta for testing.

**Comment by mkiol** [comment]
Added in: 64191fa8ad31000c8b3d5c5057e10df572d3bb96

Change is included in v4.4.0.
