### ISSUE TITLE
Feature Request Clarifications and Guidelines Inquiry

### ISSUE THREAD

**Issue by SirNoName2705** [mkiol/dsnote#77]
Hey, I absolutely admire your project. I was about to start working on a STT/TTS editor myself, with a slightly different focus, but it seems like you've implemented it much better than I could at this stage. I have several ideas, feature requests, enhancements, and questions. However, before diving into writing them down, I wanted to find out a few things:

1. Would you prefer that I submit issues on GitLab or GitHub?
   I use both platforms and am unsure which one is your main platform or if you automatically sort submissions across both.

2. Should I compile all my ideas and suggestions into one ticket or split them into multiple tickets beforehand?
   I want to minimize the workload for you. However, I'm not sure if it's more challenging for you to process several smaller tickets or one comprehensive ticket.

3. Where can I find the roadmap, if there is one available for public viewing?
   I certainly don't want to suggest things you've already planned or that others have proposed. Naturally, I'll check the existing issues on both here and GitLab, but I wanted to be sure not to create more reading work for you.

4. Is there any specific format you prefer for submissions?
   I couldn't find a ticket template and can't add tags or such. Therefore, I'd like to know how you prefer to receive feature requests.

**Comment by mkiol** [comment]
> Hey, I absolutely admire your project

Thank you :)

> Would you prefer that I submit issues on GitLab or GitHub?

If you already on GitHub, I slightly prefer GitHub (but very slightly). 

I have decided to maintain GitLab mirror as well because I don't want to force anyone to create a Github account if they don't want to do so. I must say, I am concerned about this massive centralization of open source collaboration on a single platform controlled by a single commercial entity... and thanks to GitLab mirror I always have a way to escape ;-)

> Should I compile all my ideas and suggestions into one ticket or split them into multiple tickets beforehand?

Definitely "split" approach would be easier for progress tracking, but if the features/ideas are somehow connected, report them in a single Issue. Honestly I don't have any specific rules for this. 

> Where can I find the roadmap, if there is one available for public viewing?

Right now, the roadmap is only in my mind - sorry. I am planing to create a section in readme with plans for two versions ahead but it is not done yet.

> Is there any specific format you prefer for submissions?

There is no template. Just write in plain words.

**Comment by mkiol** [comment]
Please re-open if you need more information.
