### ISSUE TITLE
avx not supported by bergamot needs it

### ISSUE THREAD

**Issue by Botox200** [mkiol/dsnote#88]
While trying to get any translation i always get the message
`avx not supported by bergamot needs it`.

So speech recognition works - translation failes.

`cat /proc/cpuinfo | grep avx` returns nothing.
cpu : Intel(R) Celeron(R) N4120 CPU @ 1.10GHz

Is there any support for non-avx-cpus?

**Comment by mkiol** [comment]
Thanks for the report.

Indeed, currently `bergamot` (a library behind machine translations) is compiled only in two versions: with AVX+AVX2 and with AVX-only. When AVX2 is not available, the fallback is to AVX-only version. In case your CPU, AVX is also not supported, therefore the fallback doesn't work. 

In theory, I might provide also second fallback to non-AVX, but the problem is that I wasn't able to successfully compile `bergamot` without AVX. According to documentation, this should be possible, but I ran into compilation errors in dependencies of `bergamot` that apparently need AVX support.

I must say I didn't spend a lot time to resolve this problem because I thought that AVX is widely supported, but your report is clear evidence that is not true. I will try to look deeper into this problem and let you know if anything can be done.

**Comment by Botox200** [comment]
Thank you very much for the detailed explanation. 
I will probably have to run the program on another computer.

**Comment by h9j6k** [comment]
Hi Michal,

I just came across the builds by bergamot devs below, 

https://github.com/XapaJIaMnu/translateLocally/releases

They seem to have managed to build for very old arch x86_64 without avx (the ones without avx in the download names), will you be able to have a look at their repo?

Thanks.

**Comment by mkiol** [comment]
@h9j6k Thanks for the info. I will take a look at it.

**Comment by h9j6k** [comment]
> @h9j6k Thanks for the info. I will take a look at it.

You're da best!

Actually, I tried their mac builds with and without avx on an old mac. Without avx, it can translate 550 words/sec, and with avx, speed goes up to 650 words/sec. So  there is a 20% improvement, not that significant. I would say if Speech Note can run without avx on old machines, it would be great since running without avx is not that bad after all.

**Comment by mkiol** [comment]
New version 4.6.0 comes without the requirement for AVX. The `bergamot` is compiled in two versions:  AVX and non-AVX, so AVX2 is not used at all. Still there is hard requirement for SSE4.1 but is widely supported.

BTW, I had the same results as you, the difference in speed between AVX and non-AVX is very small. 

Change: 07b6cf823b9ef45d393b9fe81cd3ab2ead8ffb8d

The new version should be available in Flathub tomorrow.
